### ISSUE TITLE
Workspace namespace occurrences when publishing attachments

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/sgov#115]
There are some instances of "pracovní-prostor" IRIs when publishing diagrams.

1) Attachments file (within a vocabulary) - both predicate and object within a triple.

![image](https://user-images.githubusercontent.com/141302/146372258-980f6984-a0e8-4e61-9f4b-99058fc847b8.png)

2) Attachment file - main IRI, RDF type.

![image](https://user-images.githubusercontent.com/141302/146372534-db520615-3d71-40c5-b418-882eca7d23a0.png)

**Comment by psiotwo** [comment]
Seems ok to me - in milestone 1a the IRIs still refer to PP ontology, because we didn't move the properties into the vocabulary contexts. Or not?
