### ISSUE TITLE
Adding a vocabulary to a workspace fails if it contains an attachment that is already added to the vocabulary

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/sgov#132]
Use case: there are two vocabularies that share one attachment (e.g. a diagram). This can easily happen if you edit multiple vocabularies at once in OntoGrapher (diagrams are attached to all vocabularies). The issue is that when you try to add such vocabularies to one workspace, the API returns an error because of attachment duplication.

Steps to reproduce:
1) Create a workspace in Mission Control
2) Add a vocabulary that contains a diagram
3) Add another vocabulary that contains the same diagram => The SGoV API throws an error. In reality the vocabulary is added to the workspace, but the user does not know about it
4) Refresh the page - you should see the second vocabulary in the workspace.

The API returns 409 with the following message (example): `"Unable to add https://slovník.gov.cz/datový/pracovní-prostor/pojem/příloha/instance-56f7f04e-2c6e-4bc8-898a-3b8b5678e362 to workspace https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-705327162. It is already present in the workspace within context https://slovník.gov.cz/datový/pracovní-prostor/pojem/příloha/instance-56f7f04e-2c6e-4bc8-898a-3b8b5678e362."`

You can test this on the dev instance with the following vocabularies:
https://slovník.gov.cz/generický/evaluace-5-směrnice-rady-1999-37-es
https://slovník.gov.cz/generický/evaluace-5-zákon-č-56-2001-sb
https://slovník.gov.cz/generický/evaluace-5-semiceu-vehicle-registration-certificate-evidence
https://slovník.gov.cz/generický/evaluace-5-registr-vozidel

**Comment by Mighantos** [comment]
This issue was fixed by PR #135 and #146 (Milestone 1ba)
