### ISSUE TITLE
Adjust publishing process to account for new data architecture

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/sgov#138]
Implement changes to the publishing process so that it takes into account the new data architecture that is driven by vocabulary contexts, not workspaces.

The process will still be triggered per workspace, but there may be some data model related changes that need to be taken care of. It is possible that the server will work alright without any changes, but we need to double check everything nevertheless.

**Comment by blcham** [comment]
It confuses me that you wrote: "It is possible that the server will work alright without any changes". But we need to change REST-API right?

The publishing process is easy to update, but again I believe the biggest issue is to define the proper REST-API that you want. Or at least any REST-API that you would think of at first.

So should it be something like?:
`vocabularies/publish?vocabulary=XXXX&vocabulary=YYYY` 

------
The explanation why fixing the publishing process without defining REST-API is easy:
- what is done:
   - `ma-přílohu` is already attached to slovnik not workspace, see e.g. [turisticke-cile-příloha](https://github.com/opendata-mvcr/ssp/blob/master/content/vocabularies/d-sgov-turistick%C3%A9-c%C3%ADle/d-sgov-turistick%C3%A9-c%C3%ADle-p%C5%99%C3%ADlohy.ttl) 

  - I assume this won't be published
      - related vocabulary contexts
      - relation between vocabularies "importuje-slovnik" unless it is already in the vocabulary
- what needs to be done:
  - make sure that the output model is compliant with [specification in milestone-1b](https://docs.google.com/document/d/1NAwSgQGoOhnFcQ-oko5Rf6lgOYV5BVSpu1nAaEP1ZlQ/edit#heading=h.qc0e7gycn2qi)
  - make sure that all data are already migrated so they are compliant with that specification

**Comment by karelklima** [comment]
> But we need to change REST-API right?

I certainly hope not. Publishing is triggered from MC and that will remain the same.

> The explanation why fixing the publishing process without defining REST-API is easy

That's why I wrote originally that it is possible that everything will just work alright without any changes.

**Comment by blcham** [comment]
I believe that no implementation is needed and this ticket can be closed.

**Comment by karelklima** [comment]
Attachments will be linked to vocabulary contexts, not to the metadata context - so this change will be needed.

**Comment by blcham** [comment]
Tested on sample workspace:
https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/workspace/instance-1805738405

Here is published pull request:
https://github.com/opendata-mvcr/ssp/pull/507
