### ISSUE TITLE
Workspaces endpoints returns different last modified date from the single workspace endpoint.

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/sgov#72]
Case

- workspace: https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1759811010
- lastModified according to the /workspaces endpoint: **1600860010129**
- lastModified according to /workspaces/instance-1759811010: **1600184670064**

**Comment by psiotwo** [comment]
Cannot find the referenced workspace. Tried two other workspaces instance1170301076 and instance69809529, and for them both endpoints return the same time.

Feel free to reopen with a reference to a problematic workspace.

**Comment by karelklima** [comment]
This is another example: https://mission-control.netlify.app/workspaces/instance-662374584
lastModified in workspaces: 1600507752395
lastModified in detail: 1599724074335

**Comment by psiotwo** [comment]
Can see it - funny thing is that I cannot reproduce it when running locally :facepalm:, just on the KBSS server. Going to take a look, maybe some localization setup ...

**Comment by psiotwo** [comment]
@karelklima should be resolved. Checked on some workspaces. Please test.

**Comment by psiotwo** [comment]
Closing. Please reopen in case the problem is back.
